name: longpress_popup_example
description: A new Flutter project.

publish_to: "none"

version: 2.0.0

environment:
    sdk: ^3.11.0

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8

    latlong2: ^0.9.1
    flutter_map: ^8.2.2
    google_fonts: ^8.0.2
    longpress_popup:
        path: ../

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^1.0.0
    flutter_native_splash: ^2.4.7
    flutter_launcher_icons: ^0.14.4

flutter:
    uses-material-design: true
    assets:
        - assets/markers/
        - assets/branding/
