name: longpress_popup
description: This Flutter package extends flutter_map to easily show customizable popups when markers are long-pressed. It lets you add images, text, and buttons, and provides methods to programmatically show or hide popupsâ€”making map interactions simple and seamless.
version: 3.0.1
repository: https://github.com/ymrabti/fluttermap_markerpopup
homepage: https://github.com/ymrabti

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  vector_math: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
