name: longpress_popup
description: This Flutter package extends flutter_map to easily show customizable popups when markers are long-pressed.
version: 3.0.3+3
repository: https://github.com/ymrabti/fluttermap_markerpopup
homepage: https://longpress-popup-demo.youmti.net
documentation: https://longpress-popup-doc.youmti.net
topics:
  - flutter
  - flutter-map
  - map
  - marker
  - popup

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  vector_math: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
